service: sls-rest-api-pattern-monolitich

frameworkVersion: ">=1.1.0"

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  profile: serverless-admin
  environment:
<<<<<<< HEAD:__gabricavi/_sources/aws-node-rest-api-pattern-monolitich/serverless.yml
<<<<<<< HEAD
<<<<<<< HEAD
    DYNAMODB_TABLE_TODOS: ${self:service}-${opt:stage, self:provider.stage}
    DYNAMODB_TABLE_TODOS_RICH: ${self:service}-${opt:stage, self:provider.stage}-RICH
=======
    DYN_T_TODOS: ${self:service}-${opt:stage, self:provider.stage}-todos
    DYN_T_CONTACTS: ${self:service}-${opt:stage, self:provider.stage}-contacts
>>>>>>> de4f989a18eb9909f992a5a39a4c8964f6e25d2b
=======
    DYN_T_TODOS: ${self:service}-${opt:stage, self:provider.stage}-todos
    DYN_T_CONTACTS: ${self:service}-${opt:stage, self:provider.stage}-contacts
>>>>>>> 1d45983c6ddd89f20241e6eba4adcfb24320bdac
=======
    DYN_T_TODOS: ${self:service}-${opt:stage, self:provider.stage}-todos
    DYN_T_CONTACTS: ${self:service}-${opt:stage, self:provider.stage}-contacts
>>>>>>> ba7e70dc34eb3c018e4888ac0f247b0508e51cbe:LuttatiStefano/_sources/aws-node-rest-api-pattern-monolitich/serverless.yml
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
<<<<<<< HEAD:__gabricavi/_sources/aws-node-rest-api-pattern-monolitich/serverless.yml
<<<<<<< HEAD
<<<<<<< HEAD
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_TODOS}"
=======
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYN_T_TODOS}"
>>>>>>> de4f989a18eb9909f992a5a39a4c8964f6e25d2b
=======
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYN_T_TODOS}"
>>>>>>> 1d45983c6ddd89f20241e6eba4adcfb24320bdac
=======
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYN_T_TODOS}"
>>>>>>> ba7e70dc34eb3c018e4888ac0f247b0508e51cbe:LuttatiStefano/_sources/aws-node-rest-api-pattern-monolitich/serverless.yml
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYN_T_CONTACTS}"  

functions:
  monolitich-handler:
    handler: monolitich-handler.handler
    events:
      - http:
          path: todos
          method: post
          cors: true
      - http:
          path: todos
          method: get
          cors: true
      - http:
          path: todos/{id}
          method: get 
          cors: true
      - http:
          path: todos/{id}
          method: put
          cors: true          
      - http:
          path: todos/{id}
          method: delete
<<<<<<< HEAD:__gabricavi/_sources/aws-node-rest-api-pattern-monolitich/serverless.yml
<<<<<<< HEAD
<<<<<<< HEAD
          cors: true  
=======
=======
>>>>>>> 1d45983c6ddd89f20241e6eba4adcfb24320bdac
=======
>>>>>>> ba7e70dc34eb3c018e4888ac0f247b0508e51cbe:LuttatiStefano/_sources/aws-node-rest-api-pattern-monolitich/serverless.yml
          cors: true
      - http:
          path: contacts
          method: post
          cors: true
      - http:
          path: contacts
          method: get
          cors: true
      - http:
          path: contacts/{id}
          method: get
          cors: true
      - http:
          path: contacts/{id}
          method: put
          cors: true          
      - http:
          path: contacts/{id}
          method: delete
          cors: true 
<<<<<<< HEAD:__gabricavi/_sources/aws-node-rest-api-pattern-monolitich/serverless.yml
<<<<<<< HEAD
>>>>>>> de4f989a18eb9909f992a5a39a4c8964f6e25d2b
=======
>>>>>>> 1d45983c6ddd89f20241e6eba4adcfb24320bdac
=======
>>>>>>> ba7e70dc34eb3c018e4888ac0f247b0508e51cbe:LuttatiStefano/_sources/aws-node-rest-api-pattern-monolitich/serverless.yml
resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
<<<<<<< HEAD:__gabricavi/_sources/aws-node-rest-api-pattern-monolitich/serverless.yml
<<<<<<< HEAD
<<<<<<< HEAD
        TableName: ${self:provider.environment.DYNAMODB_TABLE_TODOS}
    TodosRichDynamoDbTable:
=======
        TableName: ${self:provider.environment.DYN_T_TODOS}
    ContactsDynamoDbTable:
>>>>>>> de4f989a18eb9909f992a5a39a4c8964f6e25d2b
=======
        TableName: ${self:provider.environment.DYN_T_TODOS}
    ContactsDynamoDbTable:
>>>>>>> 1d45983c6ddd89f20241e6eba4adcfb24320bdac
=======
        TableName: ${self:provider.environment.DYN_T_TODOS}
    ContactsDynamoDbTable:
>>>>>>> ba7e70dc34eb3c018e4888ac0f247b0508e51cbe:LuttatiStefano/_sources/aws-node-rest-api-pattern-monolitich/serverless.yml
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
<<<<<<< HEAD:__gabricavi/_sources/aws-node-rest-api-pattern-monolitich/serverless.yml
<<<<<<< HEAD
<<<<<<< HEAD
        TableName: ${self:provider.environment.DYNAMODB_TABLE_TODOS_RICH}    
=======
        TableName: ${self:provider.environment.DYN_T_CONTACTS}    
>>>>>>> de4f989a18eb9909f992a5a39a4c8964f6e25d2b
=======
        TableName: ${self:provider.environment.DYN_T_CONTACTS}    
>>>>>>> 1d45983c6ddd89f20241e6eba4adcfb24320bdac
=======
        TableName: ${self:provider.environment.DYN_T_CONTACTS}    
>>>>>>> ba7e70dc34eb3c018e4888ac0f247b0508e51cbe:LuttatiStefano/_sources/aws-node-rest-api-pattern-monolitich/serverless.yml
