service: sls-rest-api-pattern-monolitich

frameworkVersion: ">=1.1.0"

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  profile: serverless-admin
  environment:
<<<<<<< HEAD
    DYNAMODB_TABLE_TODOS: ${self:service}-${opt:stage, self:provider.stage}
    DYNAMODB_TABLE_TODOS_RICH: ${self:service}-${opt:stage, self:provider.stage}-RICH
=======
    DYN_T_TODOS: ${self:service}-${opt:stage, self:provider.stage}-todos
    DYN_T_CONTACTS: ${self:service}-${opt:stage, self:provider.stage}-contacts
>>>>>>> de4f989a18eb9909f992a5a39a4c8964f6e25d2b
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
<<<<<<< HEAD
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_TODOS}"
=======
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYN_T_TODOS}"
>>>>>>> de4f989a18eb9909f992a5a39a4c8964f6e25d2b
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_TODOS_RICH}"  

functions:
  monolitich-handler:
    handler: monolitich-handler.handler
    events:
      - http:
          path: todos
          method: post
          cors: true
      - http:
          path: todos
          method: get
          cors: true
      - http:
          path: todos/{id}
          method: get
          cors: true
      - http:
          path: todos/{id}
          method: put
          cors: true          
      - http:
          path: todos/{id}
          method: delete
<<<<<<< HEAD
          cors: true  
=======
          cors: true
      - http:
          path: contacts
          method: post
          cors: true
      - http:
          path: contacts
          method: get
          cors: true
      - http:
          path: contacts/{id}
          method: get
          cors: true
      - http:
          path: contacts/{id}
          method: put
          cors: true          
      - http:
          path: contacts/{id}
          method: delete
          cors: true 
>>>>>>> de4f989a18eb9909f992a5a39a4c8964f6e25d2b
resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
<<<<<<< HEAD
        TableName: ${self:provider.environment.DYNAMODB_TABLE_TODOS}
    TodosRichDynamoDbTable:
=======
        TableName: ${self:provider.environment.DYN_T_TODOS}
    ContactsDynamoDbTable:
>>>>>>> de4f989a18eb9909f992a5a39a4c8964f6e25d2b
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
<<<<<<< HEAD
        TableName: ${self:provider.environment.DYNAMODB_TABLE_TODOS_RICH}    
=======
        TableName: ${self:provider.environment.DYN_T_CONTACTS}    
>>>>>>> de4f989a18eb9909f992a5a39a4c8964f6e25d2b
