service: sls-rest-api-pattern-service

frameworkVersion: ">=1.1.0"

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  profile: serverless-admin
  environment:
<<<<<<< HEAD
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
=======
    DYN_T_TODOS: ${self:service}-${opt:stage, self:provider.stage}-todos
    DYN_T_CONTACTS: ${self:service}-${opt:stage, self:provider.stage}-contacts
>>>>>>> de4f989a18eb9909f992a5a39a4c8964f6e25d2b
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
<<<<<<< HEAD
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
=======
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYN_T_TODOS}"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYN_T_CONTACTS}"  
>>>>>>> de4f989a18eb9909f992a5a39a4c8964f6e25d2b

functions:
  todosHandler:
    handler: todos/handler.todoshandler
    events:
      - http:
          path: todos
          method: post
          cors: true
      - http:
          path: todos
          method: get
          cors: true
      - http:
          path: todos/{id}
          method: get
          cors: true
      - http:
          path: todos/{id}
          method: put
          cors: true
      - http:
          path: todos/{id}
          method: delete
          cors: true
<<<<<<< HEAD
=======
  contactsHandler:
    handler: contacts/handler.contactshandler
    events:
      - http:
          path: contacts
          method: post
          cors: true
      - http:
          path: contacts
          method: get
          cors: true
      - http:
          path: contacts/{id}
          method: get
          cors: true
      - http:
          path: contacts/{id}
          method: put
          cors: true          
      - http:
          path: contacts/{id}
          method: delete
          cors: true
>>>>>>> de4f989a18eb9909f992a5a39a4c8964f6e25d2b

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
<<<<<<< HEAD
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
=======
        TableName: ${self:provider.environment.DYN_T_TODOS}
    ContactsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYN_T_CONTACTS}   
>>>>>>> de4f989a18eb9909f992a5a39a4c8964f6e25d2b
